# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBWTdNvnxxbMQCkrh56f28cfAFEVWvJM
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from fpdf import FPDF
from io import BytesIO

BASE_DATOS = {
    "1006843545": {"nombre": "Juan Pérez", "edad": 25},
    "2345678901": {"nombre": "María López", "edad": 30},
    "3456789012": {"nombre": "Carlos Martínez", "edad": 28},
    "4567890123": {"nombre": "Laura Gómez", "edad": 35},
    "5678901234": {"nombre": "Andrés Rodríguez", "edad": 22},
}
# ==========================
# Inicializar estado
# ==========================
if "registros" not in st.session_state:
    st.session_state.registros = []

# ==========================
# Función para generar PDF
# ==========================
def generar_pdf_bytes(registros_df: pd.DataFrame) -> bytes:
    pdf = FPDF()
    pdf.add_page()

    # Cargar el logo a la izquierda
    try:
        pdf.image("logoag.png", x=10, y=10, w=35)  # Tamaño ajustado
    except:
        pass  # Si la imagen falla, continuar sin error

    # Título centrado (dejando espacio a la derecha del logo)
    pdf.set_xy(50, 15)  # Moverlo más al centro verticalmente
    pdf.set_font("Arial", "B", 18)
    pdf.cell(0, 10, "Registro de Asistencia", ln=True, align="C")

    # Espaciado después del título
    pdf.ln(15)

    # Fecha de generación (centrado y más abajo)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 10, f"Generado el: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
    pdf.ln(10)

    # Encabezados de tabla
    pdf.set_font("Arial", "B", 11)
    pdf.cell(15, 8, "N°", 1, align="C")
    pdf.cell(35, 8, "Cédula", 1, align="C")
    pdf.cell(50, 8, "Nombre", 1, align="C")
    pdf.cell(15, 8, "Edad", 1, align="C")
    pdf.cell(60, 8, "Hora", 1, align="C")
    pdf.ln()

    # Filas
    pdf.set_font("Arial", "", 10)
    for _, row in registros_df.iterrows():
        pdf.cell(15, 8, str(row["numero_registro"]), 1)
        pdf.cell(35, 8, str(row["cedula"]), 1)
        pdf.cell(50, 8, row["nombre"], 1)
        pdf.cell(15, 8, str(row["edad"]), 1)
        pdf.cell(60, 8, row["hora_registro"], 1)
        pdf.ln()

    buffer = BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    return buffer.read()



# ==========================
# Interfaz Streamlit
# ==========================
st.title("Agente de Asistencia Protocolaria")

st.write(
    "Registra asistentes por número de cédula. "
    "El sistema asigna automáticamente el número de registro y la hora."
)

# Cantidad objetivo de registros
cantidad_objetivo = st.sidebar.number_input(
    "Cantidad de registros a capturar",
    min_value=1,
    step=1,
    value=10,
    help="Cuando se llegue a esta cantidad, podrás descargar el PDF final."
)

st.sidebar.write(f"Registros actuales: **{len(st.session_state.registros)}**")

# ==========================
# Formulario de registro
# ==========================
st.subheader("Nuevo registro de asistencia")

with st.form("form_registro"):
    cedula = st.text_input("Número de cédula", help="Ingresa el número de cédula del asistente.")
    enviado = st.form_submit_button("Registrar asistencia")

    if enviado:
        cedula = cedula.strip()

        if not cedula:
            st.error("Por favor ingresa un número de cédula.")
        elif cedula not in BASE_DATOS:
            st.error("La cédula no se encuentra en la base de datos.")
        else:
            info = BASE_DATOS[cedula]
            numero_registro = len(st.session_state.registros) + 1
            hora_registro = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            st.session_state.registros.append({
                "numero_registro": numero_registro,
                "cedula": cedula,
                "nombre": info["nombre"],
                "edad": info["edad"],
                "hora_registro": hora_registro
            })

            st.success(f"✅ Registro #{numero_registro} guardado: {info['nombre']} ({info['edad']} años) — {hora_registro}")



# ==========================
# Mostrar tabla de registros
# ==========================
if st.session_state.registros:
    st.subheader("Registros actuales")
    df_registros = pd.DataFrame(st.session_state.registros)
    st.dataframe(df_registros[["numero_registro", "cedula", "nombre", "edad", "hora_registro"]], use_container_width=True)

else:
    st.info("Aún no hay registros de asistencia.")

# ==========================
# Generación del PDF
# ==========================
st.subheader("Generar documento PDF")

if len(st.session_state.registros) < cantidad_objetivo:
    st.warning(
        f"Aún no se ha alcanzado la cantidad objetivo de registros "
        f"({len(st.session_state.registros)}/{cantidad_objetivo})."
    )
else:
    st.success(
        f"Se alcanzó la cantidad objetivo de registros "
        f"({len(st.session_state.registros)}/{cantidad_objetivo})."
    )

if st.session_state.registros:
    pdf_bytes = generar_pdf_bytes(pd.DataFrame(st.session_state.registros))
    st.download_button(
        label="Descargar PDF de asistencia",
        data=pdf_bytes,
        file_name="registro_asistencia.pdf",
        mime="application/pdf",
    )
else:
    st.info("No hay registros para generar el PDF.")